### ISSUE TITLE
TypeError: Cannot convert numpy.ndarray to numpy.ndarray

### ISSUE THREAD

**Issue by A-postgraduate-student** [raghavagps/algpred2#2]
We are having the following problem with the installation of Algpred 2.0 and would appreciate a response, thanks!

##############################################################################
# The program AlgPred2.0 is developed for predicting allergenic and non allergenic #
# protein from their primary sequence, developed by Prof G. P. S. Raghava's group. #
# ############################################################################
Summary of Parameters:
Input File:  ./PR-1.fasta ; Model:  1 ; Threshold:  0.3
Output File:  outfile.csv ; Display:  1
Traceback (most recent call last):
  File "/home/weilab/algpred2_new/algpred2.py", line 268, in <module>
    CM = pd.concat([pd.DataFrame(seqid_1),pd.DataFrame(seq)],axis=1)
  File "/home/weilab/miniconda3/envs/algpred/lib/python3.9/site-packages/pandas/core/frame.py", line 867, in __init__
    mgr = ndarray_to_mgr(
  File "/home/weilab/miniconda3/envs/algpred/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 319, in ndarray_to_mgr
    values = _prep_ndarraylike(values, copy=copy_on_sanitize)
  File "/home/weilab/miniconda3/envs/algpred/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 580, in _prep_ndarraylike
    values = convert(values)
  File "/home/weilab/miniconda3/envs/algpred/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 564, in convert
    res = maybe_convert_platform(v)
  File "/home/weilab/miniconda3/envs/algpred/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 138, in maybe_convert_platform
    arr = lib.maybe_convert_objects(arr)
  File "lib.pyx", line 2538, in pandas._libs.lib.maybe_convert_objects
TypeError: Cannot convert numpy.ndarray to numpy.ndarray

**Comment by DaniDelHoyo** [comment]
Hi! I am not part of Raghava's group, but as a fellow conda environments sufferer, I could suggest you to match you numpy and pandas versions. Depending on yours, you might need to downgrade pandas or upgrade numpy, according to a quick google search. Anyway, this kind of errors arise all the time, usually googling the last error line helps. Hope it helps.
